#!/bin/bash
killall -KILL \
	adprivacyd \
	analyticsd \
	aggregated \
	assetsd \
	bulletindistributord \
	CAReportingService \
	dasd \
	duetexpertd \
	exchangesyncd \
	healthappd \
	HeuristicInterpreter \
	kbd \
	MobileGestaltHelper \
	newsd \
	powerlogHelperd \
	PowerUIAgent \
	searchpartyd \
	siriactionsd \
	siriknowledged \
	suggestd \
	webbookmarksd \
	wifianalyticsd \
	coreduetd \
	nsurlsessiond \
	2>/dev/null
exit 0

#	assistantd \
#	cloudd \
#	contextstored \
#	corespeechd \
#	druid \
#	healthd \
#	iconservicesagent \
#	locationd \
#	mediaserverd \
#	nanoprefsyncd \
#	navd \
#	nsurlsessiond \
#	pairedsyncd \
#	pkd \
#	pkreporter \
#	remindd \
#	searchd \
#	splashboardd \
#	tursd \
#	wcd \
