#!/bin/bash
killall -KILL \
	adprivacyd \
	analyticsd \
	aggregated \
	assetsd \
	bulletindistributord \
	CAReportingService \
	dasd \
	duetexpertd \
	exchangesyncd \
	healthappd \
	HeuristicInterpreter \
	kbd \
	locationd \
	mediaserverd \
	MobileGestaltHelper \
	newsd \
	powerlogHelperd \
	PowerUIAgent \
	searchd \
	searchpartyd \
	siriactionsd \
	siriknowledged \
	splashboardd \
	suggestd \
	webbookmarksd \
	wifianalyticsd \
	2>/dev/null
exit 0
