#!/bin/bash
killall -KILL \
	adprivacyd \
	analyticsd \
	aggregated \
	assetsd \
	bulletindistributord \
	CAReportingService \
	dasd \
	duetexpertd \
	exchangesyncd \
	healthappd \
	HeuristicInterpreter \
	kbd \
	MobileGestaltHelper \
	newsd \
	powerlogHelperd \
	PowerUIAgent \
	searchpartyd \
	siriactionsd \
	siriknowledged \
	suggestd \
	webbookmarksd \
	wifianalyticsd \
	coreduetd \
	nsurlsessiond \
	druid \
	distnoded \
	corespeechd \
	splashboardd \
	fitcored \
	searchd \
	2>/dev/null
exit 0

## Unconfirmed culprit
#	assistantd \
#	cloudd \
#	contextstored \
#	healthd \
#	iconservicesagent \
#	locationd \
#	mediaserverd \
#	nanoprefsyncd \
#	navd \
#	pairedsyncd \
#	pkd \
#	pkreporter \
#	remindd \
#	tursd \
#	wcd \
